### ISSUE TITLE
Use standalone (i.e. without any wire/cable/computer/phone/tablet)

### ISSUE THREAD

**Issue by dumblob** [jasineri/android-bloatware#4]
I wonder whether this could be made easy to use completely standalone - e.g. from [Termux using `adb`](https://github.com/MasterDevX/Termux-ADB/ ) (I don't know whether it works - didn't check any permissions nor anything similar).

Any plans to make it standalone?

Being dependent on another device (which itself is dependent on internet which in case of offline desktops is impossible or at least painful) or even a cable (who carries a cable with her if the phone has wireless charging) **every single time** after an Android update or app update is very frustrating.

**Comment by realKarthikNair** [comment]
If you have root, you can use termux to debloat the device without another device

**Comment by dumblob** [comment]
Thank you for confirmation this works from Termux. Unfortunately if `root` is required, then this defeats the main value of *android-bloatware* which is to **not require** root access. Anyway, some people might find this hint useful regardless.
